###################################################################################################
#                                                                                                 #
# basic application configuration                                                                 #
#                                                                                                 #
###################################################################################################
# project name
  MCR.NameOfProject=ditav

# supported languages
  MCR.Metadata.Languages=de,en,fr

# Layout
  MIR.CustomLayout.JS=project.js
  MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/ditav-editor-includes.xed

# Classification sorting
  MCR.URIResolver.Classification.Sort.mir_licenses=false
  MCR.URIResolver.Classification.Sort.mir_filetype=false
  MCR.URIResolver.Classification.Sort.noteTypes=false

###################################################################################################
#                                                                                                 #
# Solr settings                                                                                   #
#                                                                                                 #
###################################################################################################

# MCR.Solr.Proxy.WhiteList=%MCR.Solr.Proxy.WhiteList%,/selectPublic,/findPublic
# MCR.Solr.NestedDocuments=true
# MIR.Rules.Solr.Protected.RequestHandler=find,select
MCR.URIResolver.xslImports.solr-document=%MCR.URIResolver.xslImports.solr-document%,ditav-solr.xsl


###################################################################################################
#                                                                                                 #
# Access control                                                                                  #
#                                                                                                 #
###################################################################################################

# Access keys
  MCR.ACL.AccessKey.Strategy.AllowedObjectTypes=

# Access strategy
  MIR.Access.Strategy.Classifications=mir_access,state

# grant author all permissions while a document is in state new
  MCR.Access.Strategy.CreatorPermissions=read,writedb,view-derivate,deletedb

# Allow the following user roles to search after all objects
  MIR.OwnerStrategy.AllowedRolesForSearch=admin,editor,submitter



###################################################################################################
#                                                                                                 #
# Worklow configuration                                                                           #
#                                                                                                 #
###################################################################################################

  MCR.Access.Strategy.SubmittedCategoriesstate:new
  MCR.Metadata.Service.State.Category.Default=new
  MIR.Workflow.Menu=true
  MIR.Workflow.Box=true

###################################################################################################
#                                                                                                 #
# Generic mail configuration for MCRMailer                                                        #
#                                                                                                 #
###################################################################################################

# The server for outgoing mails
  MCR.Mail.Server=mailer.gbv.de

# The mail protocol
  MCR.Mail.Protocol=smtp
  MCR.Mail.Sender=%MCR.mir-module.MailSender%
  MCR.Mail.Address=

# The debug option
  MCR.Mail.Debug=false

# Encoding for the mail
  MCR.Mail.Encoding=UTF-8

# Number of send tries
  MCR.Mail.NumTries=3

# Test
#MCR.ContentTransformer.DefaultStep.Stylesheet=xsl/mir-cosmol-layout.xsl
#MCR.ContentTransformer.MyCoReWebPage.Stylesheet=xsl/MyCoReWebPage.xsl,xsl/mir-cosmol-layout.xsl
#MCR.ContentTransformer.mcr_error.Stylesheet=xsl/mcr_error.xsl,xsl/mir-cosmol-layout.xsl
#MCR.ContentTransformer.response-subselect.Stylesheet=xsl/response-join-results.xsl,xsl/response-addDocId.xsl,xsl/response-addDerivates.xsl,xsl/response.xsl,xsl/relatedItem-subselect.xsl,xsl/mir-cosmol-layout.xsl
#MCR.ContentTransformer.response.Stylesheet=xsl/response-join-results.xsl,xsl/response-addDocId.xsl,xsl/response-addDerivates.xsl,xsl/response.xsl,xsl/mir-cosmol-layout.xsl
#MCR.ContentTransformer.site.Stylesheet=xsl/site.xsl,xsl/mir-cosmol-layout.xsl
#MCR.LayoutTransformerFactory.Default.Stylesheets=xsl/mir-cosmol-layout.xsl
#MIR.Layout.Theme=cosmol
#MCR.URIResolver.xslImports.modsmeta=%MCR.URIResolver.xslImports.modsmeta%,metadata/mir-tei-viewer.xsl

###############################################################################
#                                                                             #
# Viewer Configuration                                                        #
#                                                                             #
###############################################################################
MCR.Viewer.configuration.strategy=de.gbv.reposis.ditav.DitavViewerConfigurationStrategy


###############################################################################
#                                                                             #
#  Configuration                                                              #
#                                                                             #
###############################################################################
MCR.IIIFImage.thumbnail=de.gbv.reposis.ditav.DitavTEIIIIFThumbnailImpl
MCR.Metadata.DefaultLang=en

# Deactivate IFS2 versioning stores
MCR.IFS2.Store.class.Class=org.mycore.datamodel.ifs2.MCRMetadataStore
MCR.IFS2.Store.derivate.Class=org.mycore.datamodel.ifs2.MCRMetadataStore
MCR.Metadata.Store.DefaultClass=org.mycore.datamodel.ifs2.MCRMetadataStore

MIR.Rules.ClassificationEditor.EditableClasses=%MIR.Rules.ClassificationEditor.EditableClasses%,koloe_document_classification,koloe_topic_classification,koloe_continents,koloe_period

###############################################################################
#                                                                             #
#  DOI Configuration                                                          #
#                                                                             #
###############################################################################

# FixMe: should be VZG and VZG Prefix
MCR.DOI.Prefix=10.58137
MCR.DOI.HostingInstitution=Max Weber Stiftung

# Ditav DOI Generator and Service for QED (MWS)
MCR.PI.Generator.QedDOIGenerator=org.mycore.pi.MCRGenericPIGenerator
MCR.PI.Generator.QedDOIGenerator.GeneralPattern=10.58137/$1-$2
MCR.PI.Generator.QedDOIGenerator.Type=doi
MCR.PI.Generator.QedDOIGenerator.XPath.1=/mycoreobject/metadata/def.modsContainer/modsContainer/mods:mods/mods:identifier[@type='qedid']|/mycoreobject/metadata/def.modsContainer/modsContainer/mods:mods/mods:relatedItem[@type='host']/mods:identifier[@type='qedid']
MCR.PI.Generator.QedDOIGenerator.XPath.2=string(number(substring-after(substring-after(/mycoreobject/@ID, '_'), '_')))

MCR.PI.MetadataService.MODSDOIQed=org.mycore.mods.identifier.MCRMODSDOIMetadataService
MCR.PI.MetadataService.MODSDOIQed.Prefix=10.58137

# Configuration is required, therefore service temporary disabled.
#MCR.PI.Service.DataciteQED=de.gbv.reposis.ditav.DitavFrontEndRedirectingDOIService
MCR.PI.Service.DataciteQED.MetadataService=MODSDOIQed
MCR.PI.Service.DataciteQED.RegistrationPredicate=org.mycore.pi.condition.MCRPIPublishedPredicate
MCR.PI.Service.DataciteQED.RegisterURLContext=receive/$ID
MCR.PI.Service.DataciteQED.Transformer=datacite
MCR.PI.Service.DataciteQED.Generator=QedDOIGenerator
MCR.PI.Service.DataciteQED.Namespace=http\://datacite.org/schema/kernel-4
MCR.PI.Service.DataciteQED.Schema=xsd/datacite/v4.3/metadata.xsd
MCR.PI.Service.DataciteQED.HostingInstitution=Max Weber Stiftung
MCR.PI.Service.DataciteQED.TeiPageSubPath=documents/

###############################################################################
# CMS Rights Path Mappings                                                    #
###############################################################################
MCR.Access.Strategy.Class=de.gbv.reposis.ditav.DitavExtendedMIRStrategy
# _qed -> /qed*
# _qed_gallia_pontificia_online -> /qed/gallia-pontificia-online*
DITAV.CMS.Rights.DirectoryRoleMapping._qed=mir_institutes:mws
DITAV.CMS.Rights.DirectoryRoleMapping._qed_gallia_pontificia_online=mir_institutes:mws.dhi-paris
DITAV.CMS.Rights.DirectoryRoleMapping._qed_languages_of_diplomacy=mir_institutes:mws.mwsno
DITAV.CMS.Rights.DirectoryRoleMapping._qed_soviet_survivors=mir_institutes:mws.mwsno
DITAV.CMS.Rights.DirectoryRoleMapping._qed_gazin=mir_institutes:mws.oii

